name: Chromatic

on:
  push:

jobs:
  chromatic:
    strategy:
      fail-fast: false
      matrix:
        react: [16, 17, 18]
        reactpdf: [2, 3]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clean
        run: rm -rf node_modules package-lock.json
      - name: Install
        run: npm install react@${{ matrix.react }} react-dom@${{ matrix.react }} @react-pdf/renderer@${{ matrix.reactpdf }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets[format('CHROMATIC_PROJECT_TOKEN_react{0}_pdf{1}', matrix.react, matrix.reactpdf)] }}
